- name: Copying Thinlinc packages
  copy: src={{ tl_home }} dest=/tmp/tl

- name: Installing Thinlinc packages
  shell: yum -y install /tmp/tl/*x86_64.rpm /tmp/tl/*noarch.rpm xauth

- name: Copying Thinlinc answers
  copy: src={{ mm_home }}/configs/tl_answers dest=/tmp/tl/

- name: Setting up Thinlinc
  shell: /opt/thinlinc/sbin/tl-setup -a /tmp/tl/tl_answers
  ignore_errors: yes

- name: Configuring Thinlinc web access
  lineinfile: dest=/opt/thinlinc/etc/conf.d/webaccess.hconf regexp='^listen=.*$' line='listen=443'

