- name: LDAP packages
  yum: pkg={{ item }} state=present
  with_items:
    - openldap-servers
    - openldap-clients

- name: Configuring iptables
  lineinfile: dest=/etc/sysconfig/iptables state=present line='-A INPUT -m state --state NEW -m tcp -p tcp --dport 389 -j ACCEPT' insertbefore='^-A INPUT -m state --state NEW .*'
  notify: restart iptables

- name: Setting RootDN
  lineinfile: "dest='/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif' regexp='^olcRootDN:.*' line='olcRootDN: cn=Manager,dc=mosler,dc=bils,dc=se'"
- name: Setting Suffix
  lineinfile: "dest='/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif' regexp='^olcSuffix:.*' line='olcSuffix: dc=mosler,dc=bils,dc=se'"
- name: Setting RootPW
  lineinfile: "dest='/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif' regexp='^olcRootPW:.*' line='olcRootPW:  {SSHA}SGuX86SN0jX+X4M+1Gxlih4MmjEdh+gM' state=present"
#- lineinfile: dest='/etc/openldap/slapd.d/cn=config/olcDatabase={2}bdb.ldif' regexp='by dn.base="cn[^"]"' line='by dn.base="cn=Manager,dc=mosler,dc=bils,dc=se"'
  notify: restart slapd

- name: Configuration using ldap.conf
  copy: src={{ mm_home }}/configs/ldap.conf dest=/tmp/ldap.conf
- shell: ldapadd -c -D cn=Manager,dc=mosler,dc=bils,dc=se -w ldap -f /tmp/ldap.conf
  ignore_errors: yes
- file: path=/tmp/ldap.conf state=absent
