
- name: filsluss provisioning
  hosts: filsluss
  roles:
    - common
    - nfs

- name: hnas-emulation provisioning
  hosts: hnas-emulation
  roles:
    - common
    - nfs

- name: LDAP provisioning
  hosts: ldap
  roles:
    - common
    - ldap

- name: ThinLinc provisioning
  hosts: thinlinc-master
  roles:
    - common
    - thinlinc


- name: Openstack Controller
  hosts: openstack-controller
  roles:
    - common
    - openstack-common
    - db
    - openstack-controller


- name: OpenStack networking
  hosts: networking-node
  roles:
    - common
    - openstack-common
    - openstack-network

- name: OpenStack compute
  hosts: compute*
  roles:
    - common
    - openstack-common
    - openstack-compute
        
- name: Supernode 
  hosts: supernode
  roles:
    - common
    - nfs
    - openstack-common
    - supernode
